location:
  lat: 37.70
  long: -122.40

transit:
  stops:
    - id: 14509
      operator: SF
      direction: Inbound
      name: Folsom
      arrivals_shown: 2
    - id: 14510
      operator: SF
      direction: Outbound
      name: Folsom
      arrivals_shown: 2

weather:
  mode: point-in-time    # point-in-time or timeline
  timeline: 24h          # 7d, 12h, or 24h (ignored if mode is point-in-time)

reminders:
  trash:
    enabled: true
    days: [monday, thursday]
